postgres:
  image: postgres
  environment:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
    POSTGRES_DB: ecluster
  ports:
    - "3306:5432"
redis:
  image: redis
  ports:
    - "6379:6379"
